#' Create Heatmap of Pathway Scores
#'
#' Creates a heatmap using `pheatmap` visualizing pathway scores (e.g., average
#' expression of pathway genes) across samples. Input matrix should have samples
#' as rows and pathways as columns. The matrix is transposed for plotting.
#'
#' @param scores_matrix A numeric matrix or data frame of pathway scores (samples x pathways).
#'        Rownames must be sample identifiers, colnames must be pathway identifiers.
#' @param sample_order Character vector or NULL. Specifies the exact order (and subset) of samples
#'        (rownames in `scores_matrix`) to include in the heatmap columns. If NULL (default),
#'        uses all samples in their original order.
#' @param annotation_col Data frame or NULL. Sample annotations for column annotation bars.
#'        Rownames must match the sample names being plotted. Default: NULL.
#' @param annotation_colors List or NULL. A list specifying colors for annotation tracks,
#'        matching the structure required by `pheatmap`. Default: NULL.
#' @param title Character, title for the heatmap (default: "Pathway Scores Heatmap").
#' @param gaps_col Numeric vector or NULL. Column indices (referring to the final sample order)
#'        where to draw vertical gaps in the heatmap (default: NULL).
#' @param db_type Character or NULL. Optional database type used for cleaning pathway names
#'        (colnames of `scores_matrix`) by removing standard prefixes (e.g., "KEGG_", "GOBP_")
#'        and replacing underscores with spaces. Default: NULL (no cleaning).
#' @param scale Character, scaling parameter passed to `pheatmap`: "row" (default, scales pathways),
#'        "column" (scales samples), or "none".
#' @param color_palette Vector of colors generated by a palette function
#'        (default: `grDevices::colorRampPalette(c("navy", "white", "red"))(50)`).
#' @param cluster_rows Logical, whether to cluster rows (pathways) (default: TRUE).
#' @param show_rownames Logical, whether to show pathway names as rownames (default: TRUE).
#' @param base_fontsize Numeric, base font size for the heatmap (default: 9).
#' @param ... Additional arguments passed directly to `pheatmap::pheatmap`.
#'
#' @return The `pheatmap` object, returned invisibly. The plot is NOT saved automatically.
#' @export
#' @import pheatmap
#' @importFrom dplyr %>%
#' @importFrom stringr str_replace_all
#' @importFrom grDevices colorRampPalette
#'
#' @examples
#' # Assuming scores_mat, sample_ordering, sample_annot, annot_colors are prepared
#' # p_obj <- gsea_scores_heatmap(scores_mat, sample_order = sample_ordering,
#' #                              annotation_col = sample_annot,
#' #                              annotation_colors = annot_colors,
#' #                              title = "Pathway Heatmap", db_type = "KEGG")
#' # To save: pheatmap::save_pheatmap_pdf(p_obj, "scores_heatmap.pdf")

library(pheatmap) # Keep for colorRampPalette default if not imported elsewhere
library(dplyr)    # Keep for %>% pipe if used
library(stringr)  # Keep for str_replace_all if used

gsea_scores_heatmap <- function(scores_matrix,
                               sample_order = NULL,
                               annotation_col = NULL, # Default NULL
                               annotation_colors = NULL, # Default NULL
                               title = "Pathway Scores Heatmap",
                               gaps_col = NULL,
                               db_type = NULL,
                               scale = "row",
                               color_palette = grDevices::colorRampPalette(c("navy", "white", "red"))(50),
                               cluster_rows = TRUE, # Added
                               show_rownames = TRUE, # Added
                               base_fontsize = 9, # Added
                               ...) { # Added ellipsis

   # Validate inputs
   if (!is.matrix(scores_matrix) && !is.data.frame(scores_matrix)) {
       stop("scores_matrix must be a matrix or data frame")
   }
   if (is.null(rownames(scores_matrix))) {
       stop("scores_matrix must have rownames (sample IDs)")
   }
   if (is.null(colnames(scores_matrix))) {
       stop("scores_matrix must have colnames (pathway IDs)")
   }
   if (nrow(scores_matrix) == 0 || ncol(scores_matrix) == 0) {
       warning("scores_matrix is empty. Returning NULL.")
       return(invisible(NULL))
   }

   # Make a copy to avoid modifying the original
   plot_matrix <- scores_matrix

   # Determine final sample order and subset matrix
   if (!is.null(sample_order)) {
       missing_samples <- sample_order[!sample_order %in% rownames(plot_matrix)]
       if (length(missing_samples) > 0) {
           warning("Some samples in sample_order are not in the scores_matrix rownames: ", paste(missing_samples, collapse=", "))
       }
       valid_order <- sample_order[sample_order %in% rownames(plot_matrix)]
       if (length(valid_order) == 0) {
           warning("No valid samples remaining from sample_order. Using original sample order.")
           valid_order <- rownames(plot_matrix)
       }
       plot_matrix <- plot_matrix[valid_order, , drop = FALSE]
   } else {
       valid_order <- rownames(plot_matrix) # Use original order if none provided
   }

   # Clean pathway names (colnames) if db_type is provided
   if (!is.null(db_type)) {
       clean_names <- colnames(plot_matrix)
       prefixes <- list(
           hallmark = "^HALLMARK_", gobp = "^GOBP_", gomf = "^GOMF_", gocc = "^GOCC_",
           kegg = "^KEGG_", reactome = "^REACTOME_", biocarta = "^BIOCARTA_",
           wiki = "^WP_", grtd = "^GTRD_", perturb = "^CGP_"
       )
       db_key <- tolower(db_type)
       if (db_key %in% names(prefixes)) {
           clean_names <- gsub(prefixes[[db_key]], "", clean_names, ignore.case = TRUE)
       }
       clean_names <- gsub("_", " ", clean_names) # Replace underscores
       colnames(plot_matrix) <- clean_names
   }

   # Prepare annotation column subset based on final sample order (valid_order)
   if (!is.null(annotation_col)) {
       if (!all(valid_order %in% rownames(annotation_col))) {
            warning("Not all samples in the final heatmap order are present in annotation_col rownames. Annotation might be incomplete.")
            # Keep only matching samples
            valid_annot_samples <- intersect(valid_order, rownames(annotation_col))
            if(length(valid_annot_samples) > 0) {
                 annotation_col_subset <- annotation_col[valid_annot_samples, , drop = FALSE]
                 # Ensure it matches the order of plot_matrix rows (which is valid_order)
                 annotation_col_subset <- annotation_col_subset[valid_order[valid_order %in% valid_annot_samples], , drop=FALSE]
            } else {
                 annotation_col_subset <- NA # No matching samples
            }
       } else {
           annotation_col_subset <- annotation_col[valid_order, , drop = FALSE]
       }
   } else {
       annotation_col_subset <- NA # Use NA for pheatmap if no annotation provided
   }


   # Create the heatmap using pheatmap directly
   p <- pheatmap::pheatmap(
       mat = t(plot_matrix), # Transpose: pathways=rows, samples=cols
       scale = scale,
       cluster_rows = cluster_rows, # Cluster pathways (rows)
       cluster_cols = FALSE, # Keep user-defined sample order (columns)
       show_rownames = show_rownames, # Show pathway names
       show_colnames = FALSE, # Usually too cluttered to show sample names
       annotation_col = annotation_col_subset, # Use subsetted annotations
       annotation_colors = annotation_colors,
       color = color_palette,
       main = title,
       gaps_col = gaps_col,
       fontsize = base_fontsize,
       fontsize_row = max(5, base_fontsize - 1), # Adjust row font size
       fontsize_col = max(5, base_fontsize - 2), # Col names not shown, but set
       silent = TRUE, # Suppress plotting to console
       ... # Pass additional arguments to pheatmap
   )

   # Return the pheatmap object invisibly
   return(invisible(p))
}


#' Visualize Multiple GSEA Database Results as Heatmaps
#'
#' Iterates through a list of pathway score matrices (typically the output from
#' `run_pooled_gsea`) and generates/saves a heatmap PDF for each database using
#' `gsea_scores_heatmap` and `pheatmap`.
#'
#' @param gsea_pooled_results A list object, expected to be the output from `run_pooled_gsea`,
#'        containing a named list component `scores` where each element is a score matrix
#'        (samples x pathways).
#' @param annotation_col Data frame or NULL. Sample annotations for column annotation bars.
#'        Rownames must match the sample names present in the score matrices.
#' @param annotation_colors List or NULL. A list specifying colors for annotation tracks.
#' @param sample_order Character vector or NULL. Specifies the exact order (and subset) of samples
#'        to include in the heatmap columns. If NULL, uses the order from the score matrix.
#' @param output_dir Character, directory path where the heatmap PDF files will be saved.
#'        Defaults to "plots/gsea_heatmaps". Will be created if it doesn't exist.
#' @param gaps_col Numeric vector or NULL. Column indices (referring to the final sample order)
#'        where to draw vertical gaps in the heatmaps (default: NULL). Applied to all heatmaps.
#' @param min_pathways Integer, minimum number of pathways required in a score matrix
#'        to generate a heatmap (default: 1).
#' @param base_filename Character, prefix for the output filenames (default: "GSEA_Heatmap").
#'        The database name will be appended (e.g., "GSEA_Heatmap_HALLMARK.pdf").
#' @param ... Additional arguments passed to `gsea_scores_heatmap` and subsequently to `pheatmap`.
#'
#' @return A list containing the `pheatmap` objects generated for each database, returned invisibly.
#' @export
#' @import pheatmap
#' @importFrom grDevices pdf dev.off
#'
#' @examples
#' # Assuming pooled_results is the output from run_pooled_gsea(),
#' # sample_annot and annot_colors are prepared.
#' # gsea_visualize_all_databases(
#' #   gsea_pooled_results = pooled_results,
#' #   annotation_col = sample_annot,
#' #   annotation_colors = annot_colors,
#' #   sample_order = specific_sample_order, # Optional
#' #   output_dir = "results/gsea_heatmaps"
#' # )
gsea_visualize_all_databases <- function(gsea_pooled_results, # Renamed parameter
                                        annotation_col = NULL, # Default NULL
                                        annotation_colors = NULL, # Default NULL
                                        sample_order = NULL,
                                        output_dir = "plots/gsea_heatmaps",
                                        gaps_col = NULL,
                                        min_pathways = 1,
                                        base_filename = "GSEA_Heatmap", # Added base filename
                                        ...) { # Added ellipsis

    # --- Input Validation ---
    if (!is.list(gsea_pooled_results) || !("scores" %in% names(gsea_pooled_results))) {
        stop("`gsea_pooled_results` must be a list with a 'scores' component (typically from run_pooled_gsea).")
    }
    if (!is.list(gsea_pooled_results$scores)) {
         stop("`gsea_pooled_results$scores` must be a list of score matrices.")
    }
    # ------------------------

    # Create output directory if it doesn't exist
    if (!dir.exists(output_dir)) {
        message("Creating output directory: ", output_dir)
        dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
         if (!dir.exists(output_dir)) stop("Failed to create output directory: ", output_dir)
    }

    # Database-specific plot parameters (adjust width/height defaults)
    db_params <- list(
        hallmark = list(width = 8, height = 6),
        reactome = list(width = 12, height = 10),
        kegg = list(width = 10, height = 8),
        gobp = list(width = 10, height = 10),
        gomf = list(width = 9, height = 7),
        gocc = list(width = 9, height = 7),
        biocarta = list(width = 10, height = 8),
        wiki = list(width = 10, height = 8),
        grtd = list(width = 10, height = 8),
        perturb = list(width = 10, height = 8)
    )
    default_params <- list(width = 9, height = 7) # Default size

    # List to store heatmap objects
    heatmap_list <- list()

    # Process each database in the 'scores' list
    for (db_name in names(gsea_pooled_results$scores)) {
        scores_mat <- gsea_pooled_results$scores[[db_name]]

        # Skip if no scores matrix or not enough pathways
        if (is.null(scores_mat) || !is.matrix(scores_mat) || ncol(scores_mat) < min_pathways) {
            message(sprintf("Skipping heatmap for '%s': No valid score matrix or fewer than %d pathways.", db_name, min_pathways))
            next
        }

        message(sprintf("Creating heatmap for %s database (%d pathways)...", toupper(db_name), ncol(scores_mat)))

        # Get database-specific parameters or use defaults
        plot_dims <- if (tolower(db_name) %in% names(db_params)) db_params[[tolower(db_name)]] else default_params

        # Calculate dynamic height based on number of pathways (rows in transposed matrix)
        num_pathways <- ncol(scores_mat)
        # Adjust height more gradually
        dynamic_height <- plot_dims$height + max(0, (num_pathways - 15) * 0.15)
        dynamic_height <- max(plot_dims$height * 0.8, dynamic_height) # Ensure a minimum reasonable height

        # Create title
        heatmap_title <- paste0("GSEA ", toupper(db_name), " Pathway Scores")

        # Generate filename
        clean_db_name <- gsub("[^A-Za-z0-9_]+", "_", toupper(db_name)) # Sanitize db name
        filename <- file.path(output_dir, paste0(base_filename, "_", clean_db_name, ".pdf"))

        # Create the heatmap object using the updated function (which doesn't save)
        # Pass additional arguments (...)
        p_obj <- tryCatch({
            gsea_scores_heatmap(
                scores_matrix = scores_mat,
                sample_order = sample_order,
                annotation_col = annotation_col,
                annotation_colors = annotation_colors,
                title = heatmap_title,
                gaps_col = gaps_col,
                db_type = db_name, # Pass db_name for potential name cleaning
                ... # Pass extra args like scale, cluster_rows etc.
            )
        }, error = function(e) {
             warning(sprintf("Failed to generate heatmap object for '%s': %s", db_name, e$message))
             return(NULL)
        })


        # Save the plot if object creation was successful
        if (!is.null(p_obj)) {
             tryCatch({
                 # Use pheatmap's saving capability or standard pdf device
                 # Using standard device for more control:
                 grDevices::pdf(filename, width = plot_dims$width, height = dynamic_height)
                 print(p_obj) # Print the pheatmap object to the device
                 grDevices::dev.off()
                 message("Heatmap saved to: ", filename)
                 heatmap_list[[db_name]] <- p_obj # Store the object
             }, error = function(e) {
                  warning(sprintf("Failed to save heatmap PDF for '%s' to '%s': %s", db_name, filename, e$message))
                  # Ensure device is closed if error occurred during plotting
                  if (names(grDevices::dev.cur()) != "null device") grDevices::dev.off()
             })
        }
    }

    message(sprintf("Completed heatmap visualization. Processed %d databases.", length(gsea_pooled_results$scores)))

    return(invisible(heatmap_list))
}
